# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading Dataset

In [5]:
df = pd.read_csv("student_datasets.csv")
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [6]:
df.tail()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
4419,1,1.0,6.0,9773.0,1,1,125.0,1,1,1.0,...,0,6.0,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,1,1.0,2.0,9773.0,1,1,120.0,105,1,1.0,...,0,6.0,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,1,1.0,1.0,9500.0,1,1,154.0,1,37,37.0,...,0,8.0,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,1,1.0,1.0,9147.0,1,1,180.0,1,37,37.0,...,0,5.0,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,1,10.0,1.0,9773.0,1,1,152.0,22,38,37.0,...,0,6.0,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

# Description of dataset

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   str
 1   Application mode                                4423 non-null   float64
 2   Application order                               4423 non-null   float64
 3   Course                                          4421 non-null   float64
 4   Daytime/evening attendance                      4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4420 non-null   float64
 7   Nacionality                                     4424 non-null   str
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4423 non-null   float64
 10  Mother's occupation                             4423 non-null   float64
 11  Father's occupation                             4423 non-null   str
 12  Admission grade                                 4422 non-null   float64
 13  Displaced                                       4424 non-null   str
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4423 non-null   float64
 16  Tuition fees up to date                         4423 non-null   str
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4423 non-null   str
 20  International                                   4423 non-null   float64
 21  Curricular units 1st sem (credited)             4424 non-null   str
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4423 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4423 non-null   float64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4423 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
 36  Target                                          4424 non-null   str
dtypes: float64(15), int64(14), str(8)
memory usage: 1.2 MB

In [8]:
df.describe()

,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Mother's qualification,Father's qualification,Mother's occupation,Admission grade,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
count,4423.000000,4423.000000,4421.000000,4424.000000,4424.000000,4420.000000,4424.000000,4423.000000,4423.000000,4422.000000,...,4424.000000,4424.000000,4423.000000,4424.000000,4424.000000,4423.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,18.663351,1.727560,8856.331147,0.890823,4.577758,132.621561,19.561935,22.271987,10.961338,126.988512,...,0.137658,0.541817,6.231743,8.063291,4.435805,10.229941,0.150316,11.566139,1.228029,0.001969
std,17.482509,1.313802,2064.221611,0.311897,10.216592,13.189209,15.603186,15.343244,26.421223,14.476775,...,0.690880,1.918546,2.196038,3.947951,3.014764,5.211367,0.753774,2.663850,1.382711,2.269935
min,1.000000,0.000000,33.000000,0.000000,1.000000,95.000000,1.000000,1.000000,0.000000,95.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
25%,1.000000,1.000000,9085.000000,1.000000,1.000000,125.000000,2.000000,3.000000,4.000000,117.900000,...,0.000000,0.000000,5.000000,6.000000,2.000000,10.750000,0.000000,9.400000,0.300000,-1.700000
50%,17.000000,1.000000,9238.000000,1.000000,1.000000,133.100000,19.000000,19.000000,5.000000,126.100000,...,0.000000,0.000000,6.000000,8.000000,5.000000,12.200000,0.000000,11.100000,1.400000,0.320000
75%,39.000000,2.000000,9556.000000,1.000000,1.000000,140.000000,37.000000,37.000000,9.000000,134.800000,...,0.000000,0.000000,7.000000,10.000000,6.000000,13.333333,0.000000,13.900000,2.600000,1.790000
max,57.000000,9.000000,9991.000000,1.000000,43.000000,190.000000,44.000000,44.000000,194.000000,190.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,16.200000,3.700000,3.510000

In [10]:
df.shape

(4424, 37)

# Exploratory Data Analysis (EDA)
# Data Preparation and Cleaning

# Rename Column

In [11]:
df.rename(columns={'Nacionality':'Nationality'}, inplace=True)

In [12]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nationality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

# Missing values

In [13]:
df.isnull().sum()

Marital status                                    0
Application mode                                  1
Application order                                 1
Course                                            3
Daytime/evening attendance                        0
Previous qualification                            0
Previous qualification (grade)                    4
Nationality                                       0
Mother's qualification                            0
Father's qualification                            1
Mother's occupation                               1
Father's occupation                               1
Admission grade                                   2
Displaced                                         0
Educational special needs                         0
Debtor                                            1
Tuition fees up to date                           1
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 1
International                                     1
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  1
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               1
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  1
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

# Checking the unique features of all the missing values

In [14]:
df['Marital status'].unique()

<StringArray>
['1', '2', '4', '?', '3', '5', '6']
Length: 7, dtype: str

In [15]:
df['Application mode'].unique()

array([17., 15.,  1., 39., 18., 53., 44., 51., 43.,  7., 42., 16.,  5.,
        2., 10., 57., 26., 27., nan])

In [16]:
df['Application order'].unique()

array([ 5.,  1.,  2.,  4.,  3.,  6., nan,  9.,  0.])

In [17]:
df['Course'].unique()

array([ 171., 9254., 9070., 9773., 8014., 9991., 9500., 9238., 9670.,
       9853., 9085., 9130., 9556., 9147., 9003.,   33., 9119.,   nan])

In [18]:
df['Previous qualification (grade)'].unique()

array([122. , 160. , 100. , 133.1, 142. , 119. , 137. , 138. , 139. ,
       136. , 133. , 110. , 149. , 127. , 135. , 140. , 125. , 126. ,
       151. , 115. , 150. , 143. , 130. , 120. , 103. , 154. , 132. ,
       167. , 129. , 141. , 116. , 148. , 118. , 106. , 121. , 114. ,
       124. ,   nan, 123. , 113. , 111. , 131. , 158. , 146. , 117. ,
       153. , 178. ,  99. , 134. , 128. , 170. , 155. , 145. , 152. ,
       112. , 107. , 156. , 188. ,  96. , 161. , 166. , 147. , 144. ,
       102. , 101. , 180. , 172. , 105. , 108. , 165. , 190. , 162. ,
       164. , 163. , 159. , 117.4, 175. , 133.8, 176. , 168. , 139.3,
        97. , 157. , 140.8, 184.4, 148.9, 109. , 174. , 182. , 138.6,
        95. , 154.4, 163.3, 145.7, 123.9, 124.4, 169. , 177. , 138.7,
       119.1, 118.9, 126.6])

In [19]:
df['Nationality'].unique()

<StringArray>
[  '1',  '62',   '6',  '41',  '26', '103',  '13',  '25',  '21', '101',  '11',
  '22',  '32', '100',  '24', '109',   '2', '108', '105',  '14',   '?',  '17']
Length: 22, dtype: str

In [20]:
df["Father's qualification"].unique()

array([12.,  3., 37., 38.,  1., 19.,  5.,  4., 34.,  2., 39., 11.,  9.,
       nan, 36., 26., 40., 14., 20., 35., 41., 22., 13., 29., 43., 18.,
       42., 10.,  6., 30., 25., 44., 33., 27., 31.])

In [21]:
df["Mother's occupation"].unique()

array([  5.,   3.,   9.,   7.,   4.,   1., 125.,   0.,   6.,   2.,  90.,
         8.,  nan, 141., 175.,  99., 191., 151., 194., 192., 132., 152.,
       134.,  10., 143., 123., 173., 193., 122., 144., 131., 171., 153.])

In [22]:
df["Father's occupation"].unique()

<StringArray>
[   '9',    '3',    '7',   '10',    '5',    '8',    '4',    '1',    '2',
  '124',    '6',    '0',   '90',  '175',  '121',   '99',  '144',  '195',
  '192',  '161',  '193',  '151',  '182',  '132',  '131',  '194',  '163',
  '135',  '143',  '171',  '103',  '172',  '152',  '183',  '122',  '102',
  '181',  '134',  '123',  '112',  '153',  '174',  '141',  '114',    nan,
 'Five',  '101',  '154']
Length: 48, dtype: str

In [23]:
df["Admission grade"].unique()

array([127.3, 142.5, 124.8, 119.6, 141.5, 114.8, 128.4, 113.1, 129.3,
       123. , 130.6, 119.3, 130.2, 111.8, 137.1, 120.7, 137.4, 136.3,
       124.6, 120.3, 121.8, 125.5, 114.9, 123.9, 157. , 116.4, 131. ,
       122.1, 118.8, 150. , 130. , 138.8, 134.5, 131.4, 102.5, 128.8,
       122.9, 113.9, 120. , 121.1, 120.4, 100.6, 121.4, 109.7, 134.1,
       127.6, 132.4, 133.4, 126.1, 113.5, 121.3, 159.3, 129.1, 155.3,
       139.8, 115.2, 131.9, 126. , 120.9, 128.2, 120.1, 100. , 134. ,
       130.8, 135.8, 111.7, 132.9, 115.5, 106. , 117. , 110.2, 155.7,
       180.4, 110. , 161. , 117.6, 128.7, 112.2, 100.8, 105. , 114. ,
       137. , 124.9, 134.3, 111.5, 160. , 117.4, 122.2, 118.2, 106.7,
       108.2, 107. , 136.1, 115.3, 140.4, 113.4, 118.6, 122.3, 127.9,
       117.1, 145.3, 122.6, 128. , 123.7, 131.7, 133.2, 109.3, 113. ,
       157.9, 112.1, 174.7, 110.1,  99.7, 121. , 119.1, 124.7, 117.2,
       131.5, 121.7, 123.4, 132.8, 108.7, 138.1, 126.5, 127.4, 123.6,
       122. , 125.8, 123.3, 124.4, 170. , 121.5,   nan, 132.3, 148. ,
       113.3, 133. , 140. , 128.3, 104. , 135. , 126.6, 129. , 162.3,
       163.4, 122.8, 118. , 129.8, 152. , 131.8, 105.9, 132.1, 129.5,
       126.7, 116.5, 149.8, 115.1, 124.5, 136. , 126.3, 126.9, 145. ,
       115.8, 147. , 122.5, 117.5, 127.5, 133.3,  97. , 112. , 130.5,
       141.7, 119.7, 119.4, 155. , 122.7, 117.9, 116.8, 125.4, 127.2,
       103.4, 123.2, 124.1,  99.5, 110.8, 118.9, 121.6, 149.2, 126.2,
       127.8, 113.7, 117.8, 136.7, 144.7, 142.3, 143. , 100.1, 101. ,
       116. , 135.6, 118.7, 125.7, 107.1, 127. , 154.4, 116.1, 118.5,
       146.7, 124.3, 137.8, 147.8, 155.6, 130.9, 125. , 136.8, 151. ,
       103.5, 134.4, 132.5, 114.7, 166.9, 125.9, 178.3, 135.1, 136.2,
       116.3, 124.2, 127.1, 172. , 128.5, 131.2, 112.9, 140.9, 148.4,
       129.7, 119.9, 141. , 116.6, 140.2, 146.2, 156.1, 115. , 158.7,
       111.9, 114.2,  96. , 128.9, 131.3, 139. , 120.8, 150.5, 129.4,
       114.4, 114.5, 130.3, 114.6, 129.9, 114.3, 152.4, 155.1, 153.2,
       125.2, 141.3, 104.5, 113.2, 123.8, 133.8, 132.7, 106.6, 124. ,
       116.9, 130.4, 132. , 143.7, 152.8, 133.5, 101.8, 121.9, 148.8,
       126.8, 115.9, 132.2, 183.5, 100.9, 110.3, 137.2, 118.4, 144.9,
       146.8, 138. , 119.8,  95. , 144.2, 135.3, 143.9, 140.7, 118.1,
       106.5, 137.5, 102. , 133.9, 134.7, 125.3, 106.1, 139.9, 109. ,
       109.5, 131.6, 136.4, 132.6, 158. , 144.4, 143.3, 112.3, 180. ,
       136.5, 137.6, 138.4, 123.5, 142.8, 155.5, 163.5, 161.9, 166.6,
       137.7, 152.1, 162.9, 146.5, 190. , 144.3, 148.3, 107.5, 138.5,
       113.6, 143.2, 118.3, 115.6, 112.4, 154. , 111.3, 162.5, 119. ,
       131.1, 162. , 110.6, 156.9, 159.1, 149. , 129.6, 133.6, 146.9,
       109.1, 129.2, 154.1, 147.2, 151.6, 111.6, 117.3, 115.7, 134.8,
       112.6, 128.1, 143.4,  96.7, 143.1, 143.5, 151.1, 112.5, 133.1,
       151.3, 113.8, 107.7, 128.6, 134.6, 135.7, 135.5, 108. , 127.7,
       140.1, 105.5, 120.2, 145.6, 142. , 107.8, 109.4, 143.6, 119.5,
       175.6, 136.9, 101.7, 112.7, 105.8, 126.4, 164.9, 157.5, 146.6,
       142.2, 135.9, 106.8, 139.7, 146. , 108.8, 134.9, 136.6, 159. ,
       105.4, 139.1, 184. , 108.3, 147.6, 125.1, 150.3, 120.5, 120.6,
       168.5, 108.5, 138.2, 144. , 152.3, 169.7, 117.7, 159.7, 159.9,
       153.5, 123.1, 171.2, 153.9, 111. ,  98.9, 139.4, 154.8,  95.5,
       111.1, 147.7, 138.3, 141.8, 125.6, 144.1, 122.4, 116.2, 139.2,
       116.7, 155.8,  97.2, 156. , 163.7, 156.3, 153. , 141.4, 168. ,
       101.3,  98.7, 100.7, 106.2, 103. ,  98.1, 130.7, 164.3,  99. ,
       161.2, 149.9, 110.5, 137.9, 165.8, 152.5, 140.5, 104.8, 140.8,
       121.2, 133.7, 151.9, 145.4, 115.4,  97.4, 105.2, 134.2, 146.3,
       161.5, 148.7,  98. , 143.8, 138.7, 138.6, 155.2, 106.3,  97.5,
       139.6, 150.6, 184.4, 150.2, 146.1, 102.6, 153.8, 137.3, 149.3,
       119.2, 147.3, 147.5, 110.4, 148.9, 150.9,  99.3, 104.1, 176.7,
       156.8, 144.6, 153.6, 158.3, 154.9, 100.5, 107.2, 141.2, 150.4,
       138.9,  95.1, 157.7, 104.6, 178. , 161.1, 107.6, 145.2, 160.6,
       145.8,  95.8, 105.6, 110.7, 106.4, 150.1, 156.5,  98.6, 146.4,
       165.7, 156.4, 148.5, 104.7, 151.5, 139.3, 158.1, 163.3, 107.3,
       145.7, 153.1, 161.8, 150.8, 163.6, 145.9, 105.1, 144.8, 151.2,
       167.3, 168.2, 166. , 101.5, 112.8, 104.2, 102.2, 105.3, 149.5,
       130.1, 108.6, 135.4, 149.7, 169.2, 144.5, 153.7, 157.8, 152.9,
        98.5, 160.1, 160.5, 151.4, 151.7, 176. , 142.4, 141.6, 100.2,
       152.7, 173.3, 157.4, 102.4, 162.2, 159.5, 135.2, 154.5, 105.7,
       108.4, 109.8, 165.2, 103.6,  99.6, 167.1, 139.5, 154.3, 142.7,
       140.3, 103.7, 162.4,  96.1, 109.6, 149.4, 101.6, 148.6, 107.4,
       168.6, 155.9, 179.6, 141.1, 163. , 154.7, 109.9, 154.6, 148.2,
       142.6, 147.9, 160.4, 111.4, 163.1, 102.8, 162.1, 103.8, 156.2])

In [24]:
df["Displaced"].unique()

<StringArray>
['1', '0', '?']
Length: 3, dtype: str

In [25]:
df["Debtor"].unique()

array([ 0.,  1., nan])

In [26]:
df["Tuition fees up to date"].unique()

<StringArray>
['1', '0', nan, '?']
Length: 4, dtype: str

In [27]:
df["Age at enrollment"].unique()

<StringArray>
[     '20',      '19',      '45',      '50',      '18',      '22',      '21',
      '34',      '37',      '43',      '55',      '39',      '29',      '24',
      '27',      '23',      '26',      '33',      '35',      '25',      '44',
      '36',      '47',      '28',      '38', 'UnKnown',      '30',      '31',
      '32',      '40',      '42',      '48',      '49',      '46',      '41',
      '70',      '60',      '53',      '51',      '52',      '54',      '61',
      '58',      '59',      '17',      '57',      '62',       nan]
Length: 48, dtype: str

In [28]:
df["International"].unique()

array([ 0.,  1., nan])

In [29]:
df["Curricular units 1st sem (credited)"].unique()

<StringArray>
[ '0',  '2',  '3',  '6',  '7', '13',  '4',  '1',  '5', '19', '11',  '8', '10',
  '9', '15', '12', '14', '18', '17', '16', '20', 'Na']
Length: 22, dtype: str

In [30]:
df["Curricular units 1st sem (grade)"].unique()

array([ 0.        , 14.        , 13.42857143, 12.33333333, 11.85714286,
       13.3       , 13.875     , 11.4       , 13.21428571, 10.57142857,
       13.25      , 13.2       , 12.        , 13.30625   , 12.5       ,
       11.66666667, 11.4375    , 12.85714286, 13.375     , 13.29666667,
       11.6       , 11.375     , 12.66666667, 12.93333333, 12.83333333,
       11.33333333, 12.4       , 10.        , 11.        , 12.75      ,
       14.8       , 13.928     , 13.        , 11.5       , 13.51666667,
       13.66666667, 11.83333333, 14.71428571, 10.6       , 13.04444444,
       14.935     , 13.13333333, 11.9       , 12.57142857, 11.2       ,
       11.975     , 10.33333333, 10.5       , 14.84285714, 12.2       ,
       12.16666667, 13.08      , 10.66666667, 11.875     , 13.75      ,
       14.2       , 11.96      , 12.875     , 14.63157895, 13.26666667,
       13.85714286, 13.4       , 12.51666667, 11.61666667, 13.14285714,
       12.6       , 10.8       , 12.8       , 14.16666667, 12.1       ,
       13.46714286, 13.2375    , 14.83333333, 13.188     , 17.125     ,
       13.605     , 13.86333333, 13.33333333, 12.25      , 13.16666667,
       12.85555556, 14.91875   , 14.25714286, 11.25      , 12.45714286,
       11.68333333, 11.75      , 11.95      , 14.35      , 12.61904762,
       13.05      , 12.24285714, 12.93375   , 11.81666667, 11.16666667,
       12.32428571, 11.14285714, 12.91428571, 13.83333333, 13.71428571,
       12.64285714, 12.91666667, 15.625     , 11.71428571, 12.125     ,
       13.85      , 13.74166667, 15.33333333, 11.57142857, 13.5       ,
       12.47142857, 12.90909091, 12.9       , 13.22      , 13.15142857,
       15.        , 14.4       , 16.        , 13.57142857, 14.82857143,
       13.67142857, 12.67      , 14.5       , 13.68571429, 11.55555556,
       13.79714286, 14.00375   , 13.8       , 10.83333333, 13.385     ,
       15.66666667, 14.33333333, 11.42857143, 14.72571429, 12.86      ,
       15.11666667, 15.2       , 16.2       , 14.54285714, 13.69428571,
       11.28571429, 11.75714286, 13.05857143, 14.3       , 11.8       ,
       13.39125   , 10.69230769, 12.58571429, 13.98      , 16.15384615,
       14.03333333, 13.41428571, 13.54545455, 15.13571429, 12.28571429,
       12.74      , 12.55555556, 11.27272727, 14.66666667, 14.85714286,
       11.72727273, 14.73142857, 13.61538462, 15.8       , 14.65428571,
       12.40142857, 11.5875    , 15.23076923, 12.90142857, 14.14285714,
       13.25375   , 13.78571429, 13.91666667, 12.08285714, 13.81428571,
       11.3       , 12.3       , 12.69428571, 14.4125    , 12.92875   ,
       14.40285714, 13.38142857, 14.13125   , 13.6       , 13.84615385,
       16.4       , 13.81818182, 10.2       , 11.44444444, 13.31      ,
       13.48714286, 13.96666667, 11.98      , 11.61428571, 14.31428571,
       12.76666667, 14.70625   , 11.81428571, 12.77125   , 11.72142857,
       14.75      , 10.75      , 12.61      , 13.625     , 11.69      ,
       14.52857143, 15.95714286, 12.625     , 13.49666667, 11.77777778,
       12.42857143, 12.5075    , 12.09090909, 14.6       , 13.82857143,
       12.5375    , 12.1625    , 12.45      , 11.45454545, 11.88888889,
       16.88571429, 13.05555556, 12.35571429, 12.35714286, 12.84714286,
       12.34      , 13.73125   , 10.88888889, 13.025     , 12.04285714,
       12.8375    , 12.62857143, 14.26875   , 12.22857143, 15.375     ,
       12.61428571, 10.92307692, 15.83333333, 13.3625    , 15.4       ,
       12.81818182, 13.39473684, 14.25      , 13.44444444, 11.8375    ,
       12.68421053, 17.33333333, 13.11111111, 14.11111111, 14.72727273,
       13.10571429, 11.84615385, 14.42857143, 12.14285714, 13.47142857,
       13.105     , 15.5       , 12.22222222, 14.125     , 15.16666667,
       15.14285714, 13.41142857, 14.668     , 13.345     , 14.53714286,
       13.08714286, 14.14571429, 14.45      , 15.71428571, 13.46285714,
       12.41428571, 14.01666667, 10.4       , 13.91428571, 13.76111111,
       13.84285714, 14.68285714, 18.        , 11.46153846, 14.24444444,
       12.6       , 14.01428571, 12.8875    , 12.95      , 13.09428571,
       13.7       , 11.70571429, 15.28571429, 13.46666667, 14.875     ,
       14.72857143, 14.46      , 16.5       , 15.22857143, 12.77777778,
       13.128     , 11.605     , 13.18181818, 12.98125   , 11.68      ,
       13.175     , 13.31428571, 12.79142857, 11.625     , 11.99444444,
       14.1       , 12.39666667, 15.01428571, 14.05      , 14.85      ,
       14.7875    , 12.49571429, 14.56666667, 12.68571429, 14.445     ,
       13.41666667, 13.1       , 13.53333333, 12.71428571, 13.30857143,
       14.07125   , 14.90142857, 12.65      , 12.13571429, 12.62      ,
       13.76666667, 13.11625   , 12.7       , 15.75      , 14.35555556,
       17.00555556, 12.11428571, 13.05875   , 13.28571429, 14.07142857,
       13.29714286, 13.92307692, 13.37      , 13.48571429, 12.94      ,
       13.25857143, 14.65285714, 13.72727273, 15.07      , 12.60625   ,
       13.59833333, 12.04142857, 13.76923077, 15.44444444, 15.57142857,
       13.63      , 16.9       , 12.76428571, 14.60428571, 13.57625   ,
       13.76375   , 10.71428571, 14.35714286, 13.92571429, 13.44285714,
       13.125     , 11.67777778, 16.14285714, 11.78571429, 13.42375   ,
       12.46428571, 12.375     , 13.02428571, 14.28571429, 14.38461538,
       11.98857143, 11.54545455, 16.46153846, 14.37      , 14.69625   ,
       12.85555556, 13.04      , 15.65714286, 13.33142857, 13.45454545,
       15.02857143, 11.42105263, 13.35      , 13.88125   , 13.15      ,
       12.34285714, 13.45714286, 12.90857143, 12.81666667, 11.61111111,
       13.97666667, 12.45454545, 10.98333333, 13.38461538, 16.11111111,
       13.58571429, 13.34      , 13.38888889, 13.58333333, 12.82857143,
       11.32857143, 13.03333333, 12.6875    , 10.46666667, 12.83571429,
       13.24875   , 12.54545455, 11.98333333, 10.25      , 12.51428571,
       13.30769231, 13.34285714, 14.27272727, 12.1375    , 13.52857143,
       13.6375    , 14.36      , 14.51428571, 14.7       , 16.57142857,
       15.145     , 13.76125   , 15.30769231, 14.75714286, 11.91666667,
       15.63375   , 13.38125   , 12.16      , 13.3425    , 14.175     ,
       14.15384615, 12.58823529, 13.05375   , 12.03571429, 11.53846154,
       13.11714286, 12.63636364, 15.125     , 13.72571429, 15.57      ,
       14.11428571, 13.07571429, 13.51285714, 12.288     , 12.76571429,
       14.88888889, 11.35714286, 13.88428571, 13.8875    , 13.4275    ,
       13.075     , 13.49285714, 14.58333333, 15.66      , 13.55714286,
       12.18333333, 13.435     , 13.11666667, 13.87714286, 12.94428571,
       14.26666667, 12.48375   , 13.45      , 12.48571429, 14.86857143,
       13.03      , 14.57142857, 13.3675    , 12.80833333, 13.91857143,
       13.68333333, 14.69285714, 14.035     , 11.7725    , 12.46      ,
       14.80571429, 12.725     , 13.135     , 12.85      , 14.14125   ,
       14.6625    , 12.99333333, 10.21428571, 13.54285714, 11.82857143,
       12.96666667, 14.12571429, 12.78333333, 13.44      , 12.21428571,
       12.84615385, 13.37142857, 13.38571429, 13.32857143, 14.3775    ,
       14.15      , 14.07222222, 12.63333333, 14.23333333, 15.7       ,
       16.33333333, 12.5625    , 13.78125   , 13.26      , 15.15555556,
       12.82875   , 10.875     , 12.75833333, 13.50714286, 13.61428571,
       11.97142857, 12.38571429, 14.28333333, 13.27272727, 15.115     ,
       14.56571429, 13.79666667, 14.96285714, 13.64285714, 12.15384615,
       13.40375   , 16.16666667, 11.29444444, 13.43333333, 12.74285714,
       14.93571429, 12.52857143, 12.36363636, 15.09090909, 13.05882353,
       13.39166667, 14.08571429, 10.16666667, 12.12142857, 14.22222222,
       12.49285714, 15.88571429, 14.77777778, 12.72727273, 18.875     ,
       15.08333333, 12.44428571, 12.51333333, 11.15555556, 11.575     ,
       13.19857143, 13.87571429, 13.15384615, 14.44142857, 13.2325    ,
       13.07375   , 13.46428571, 14.4025    , 15.46875   , 14.98333333,
       15.88888889, 13.98333333, 14.84285714, 12.55375   , 12.66571429,
       12.57894737, 12.002     , 13.86714286, 12.675     , 11.63571429,
       12.52608696, 16.42857143, 13.336     , 14.11571429, 12.415     ,
       14.31285714, 15.42857143, 10.85714286, 11.73333333, 13.04666667,
       13.11      , 14.41428571, 13.045     , 12.858     , 14.2525    ,
       14.06      , 15.07571429, 13.77857143, 13.07285714, 16.71428571,
       11.65833333, 14.625     , 12.56      , 13.19      , 12.77142857,
       11.71666667, 17.        , 12.21052632, 12.46153846, 11.90909091,
       13.46      , 10.36842105, 12.69230769, 14.30769231, 14.45454545,
       12.44444444, 13.6125    , 12.41428571, 14.06666667, 13.55555556,
       13.27625   , 14.375     , 12.97166667, 10.92857143, 12.75714286,
       13.67      , 14.13714286, 13.55      , 14.63636364, 12.78571429,
       13.80142857, 11.82      , 13.42222222, 14.57285714, 12.98285714,
       13.755     , 14.71111111, 14.61538462, 13.67714286, 13.95833333,
       13.3875    , 12.64833333, 13.39      , 10.9       , 15.85714286,
       12.62857143, 14.23285714, 12.32      , 12.35      , 13.09090909,
       15.94285714, 14.575     , 13.47      , 13.79857143, 10.64285714,
       14.65      , 12.26666667, 10.375     , 14.44444444, 12.50625   ,
       16.85714286, 15.11428571, 12.04      , 14.32857143, 11.71666667,
       12.58      , 14.53571429, 11.6875    , 12.84142857, 17.11111111,
       12.36      , 15.25      , 13.81375   , 11.9625    , 14.98571429,
       13.78      , 13.805     , 14.42428571, 12.07142857, 14.11      ,
        9.8       , 14.31666667, 12.72857143, 13.68142857, 11.94      ,
       13.89428571, 13.46875   , 13.41625   , 15.3       , 14.61666667,
       12.19230769, 13.9       , 11.61538462, 13.99571429, 12.88625   ,
       14.50125   , 13.56875   , 14.15375   , 12.45428571, 13.27166667,
       13.54833333, 13.2575    , 11.41666667, 11.15      , 11.67857143,
       14.48571429, 12.65714286, 13.07142857, 13.126     , 15.69230769,
       15.05263158, 12.93875   , 12.18      , 12.71857143, 11.64285714,
       12.5125    , 13.48333333, 12.565     , 13.06      , 10.28571429,
       12.27142857, 13.22222222, 13.15428571, 15.10142857, 12.41666667,
       14.93333333, 14.455     , 12.32857143, 13.27142857, 12.58333333,
       13.73166667, 12.49166667, 10.81818182, 12.87857143, 14.53846154,
       12.73333333, 13.93714286, 13.6875    , 13.398     , 11.76923077,
       13.08166667, 14.59444444, 13.17647059, 12.59125   , 11.89473684,
       12.36571429, 16.83333333, 11.125     , 14.54      , 15.67571429,
       13.18333333, 11.9725    , 13.95714286, 12.91      , 13.58      ,
       12.88888889, 14.34125   , 14.20857143, 14.30714286, 14.21428571,
       13.97142857, 15.07777778, 13.38333333, 13.01125   , 11.85      ,
       12.32777778, 12.07692308, 11.23076923, 10.98571429, 16.13142857,
       14.83857143, 13.9475    , 13.06666667, 13.74625   , 13.81714286,
       15.53846154, 14.05714286, 13.29      , 13.86166667, 15.43333333,
       15.11      , 15.79857143, 13.77571429, 14.71666667, 14.368     ,
       12.08428571, 10.74444444, 13.4173913 , 13.24285714, 13.55714286,
       14.09333333, 13.51428571, 12.74428571, 13.3125    , 14.95      ,
       14.99285714, 13.01666667, 13.32714286, 11.832     , 12.41285714,
       12.54571429, 12.51428571, 13.62857143, 13.73684211, 10.76923077,
       12.47619048, 13.29166667, 14.24      , 14.10571429, 11.96666667,
       13.3475    , 13.17571429, 13.74285714, 12.21714286, 11.07142857,
       11.325     , 11.92307692, 14.88875   , 12.4125    ,         nan,
       14.9125    ])

In [31]:
df["Curricular units 2nd sem (enrolled)"].unique()

array([ 0.,  6.,  5.,  8.,  7., 11., 12.,  9., 13., 19.,  3., 10.,  4.,
       nan, 17.,  2.,  1., 14., 15., 16., 23., 18., 21.])

In [32]:
df["Curricular units 2nd sem (grade)"].unique()

array([ 0.        , 13.66666667, 12.4       , 13.        , 11.5       ,
       14.345     , 14.14285714, 13.5       , 14.2       , 13.21428571,
       11.        , 12.        , 14.545     , 12.25      , 11.425     ,
       12.85714286, 12.28571429, 14.11428571, 13.28571429, 12.33333333,
       13.71666667, 10.57142857, 13.4       , 14.375     , 13.42857143,
       10.        , 11.6       , 15.8       , 14.34285714, 13.8       ,
       14.33333333, 13.2       , 13.77142857, 12.83333333, 14.16666667,
       11.83333333, 13.595     , 12.9       , 14.935     , 12.22142857,
       12.42857143, 10.75      , 10.8       , 13.75      , 10.85714286,
       13.33333333, 15.05555556, 11.66666667, 12.2       , 13.3       ,
       11.33333333, 13.08      , 11.2       , 13.25      , 14.47777778,
       14.23076923, 12.27272727, 12.3       , 15.        , 12.8       ,
       12.57142857, 12.51666667, 10.66666667, 11.4       , 14.        ,
       11.25      , 13.77777778, 15.01111111, 13.74285714, 14.6       ,
       11.71428571, 12.5       , 14.83333333, 12.89285714, 17.5875    ,
       12.66666667, 12.33125   , 14.17857143, 10.83333333, 11.8       ,
       11.85714286, 12.6       , 12.76111111, 15.355     , 14.25714286,
       10.5       , 13.5625    , 11.68333333, 13.16666667, 11.95      ,
       10.4       , 14.58333333, 12.78947368, 13.05      , 12.24285714,
       12.93375   , 14.42857143, 12.32428571, 12.91428571, 12.64285714,
       12.91666667, 15.85714286, 13.3125    , 14.5       , 12.19285714,
       14.9125    , 11.57142857, 14.25      , 10.33333333, 11.4625    ,
       13.55555556, 13.6       , 12.36363636, 13.22      , 13.15142857,
       10.6       , 12.16666667, 14.82857143, 13.67142857, 13.55      ,
       15.42857143, 15.3875    , 13.775     , 13.81285714, 13.83333333,
       13.385     , 14.72571429, 13.1375    , 12.86      , 13.71428571,
       16.16888889, 10.25      , 15.14285714, 16.4       , 14.88181818,
       14.35555556, 13.08333333, 13.05857143, 14.05555556, 14.66666667,
       14.57142857, 13.39125   , 13.1       , 12.30769231, 16.42857143,
       13.44285714, 13.98      , 15.75      , 14.03333333, 13.41428571,
       13.57142857, 15.2875    , 10.97857143, 11.11111111, 11.16666667,
       12.14      , 12.75      , 14.73142857, 14.8       , 14.65428571,
       12.40142857, 14.07142857, 15.6       , 15.4       , 12.375     ,
       13.09444444, 13.25375   , 14.1       , 13.91666667, 12.08285714,
       13.81428571, 11.3       , 16.        , 12.69428571, 16.05      ,
       14.0625    , 14.40285714, 13.38142857, 13.98375   , 14.09090909,
       13.45454545, 12.625     , 13.26666667, 13.31      , 13.48714286,
       13.96666667, 13.225     , 14.0375    , 14.31428571, 12.12857143,
       11.75      , 14.4775    , 13.54285714, 11.875     , 12.77125   ,
       11.72142857, 12.525     , 10.2       , 12.61      , 11.69      ,
       11.28571429, 15.01818182, 15.18888889, 13.49666667, 12.5075    ,
       13.625     , 14.71428571, 13.82857143, 12.61428571, 15.2       ,
       13.825     , 14.55555556, 11.7       , 11.54545455, 11.46153846,
       15.74444444, 15.8125    , 12.35571429, 11.98      , 12.35714286,
       13.85714286, 13.78888889, 13.01875   , 13.73125   , 13.81111111,
       12.04285714, 15.5       , 12.71428571, 12.62857143, 14.26875   ,
       13.2125    , 11.45454545, 11.70833333, 14.44444444, 13.54545455,
       13.55473684, 11.7375    , 11.22222222, 12.48125   , 12.38461538,
       17.        , 14.85714286, 12.14285714, 15.77777778, 13.10571429,
       14.4       , 17.6       , 16.575     , 11.18181818, 11.42857143,
       13.94444444, 13.105     , 11.36363636, 13.29444444, 15.625     ,
       12.7       , 14.63375   , 13.345     , 14.53714286, 13.22222222,
       12.95      , 14.28571429, 13.62777778, 14.14444444, 13.16428571,
       15.33333333, 14.01666667, 14.10625   , 12.82375   , 13.84285714,
       11.58333333, 12.23333333, 12.6       , 15.35      , 12.46153846,
       12.54545455, 12.8875    , 12.55      , 13.7       , 15.11111111,
       11.70571429, 16.075     , 13.64285714, 14.75      , 11.125     ,
       16.32727273, 17.42857143, 15.22857143, 13.19333333, 12.4125    ,
       12.90909091, 12.98125   , 11.68      , 14.875     , 13.31428571,
       15.57142857, 12.79142857, 12.43142857, 12.94285714, 16.0875    ,
       15.1       , 15.8625    , 14.67142857, 14.56666667, 12.68571429,
       14.445     , 14.625     , 13.41666667, 14.8125    , 13.61428571,
       14.07125   , 14.90142857, 12.44555556, 13.32857143, 14.05142857,
       13.11625   , 13.49375   , 16.58222222, 12.11428571, 13.05875   ,
       15.1625    , 13.29714286, 13.48571429, 13.76      , 13.25857143,
       12.6375    , 14.65285714, 11.14285714, 15.07      , 12.5125    ,
       11.9       , 11.93333333, 12.96818182, 13.14285714, 12.04142857,
       15.30769231, 15.16666667, 16.375     , 13.63      , 12.22857143,
       16.37777778, 12.76428571, 15.68333333, 13.57625   , 15.83333333,
       13.76375   , 14.35714286, 13.92571429, 13.74444444, 15.875     ,
       16.2       , 11.78571429, 13.42375   , 12.46428571, 13.02428571,
       18.57142857, 12.38      , 11.98857143, 12.88888889, 13.875     ,
       13.41111111, 14.65      , 14.62222222, 13.9125    , 13.99444444,
       11.68571429, 15.65714286, 13.33142857, 15.02857143, 12.58333333,
       11.07692308, 13.35      , 13.88125   , 15.06875   , 12.34285714,
       14.5125    , 12.90857143, 12.875     , 12.05555556, 12.55555556,
       12.04166667, 10.98333333, 14.6875    , 10.84      , 12.45714286,
       14.88888889, 13.58333333, 12.82857143, 11.32857143, 13.03333333,
       10.92307692, 14.23125   , 13.24875   , 15.61111111, 16.14285714,
       11.625     , 12.28125   , 10.44444444, 12.77777778, 12.81818182,
       11.65      , 14.81818182, 12.91111111, 14.65555556, 14.3875    ,
       14.36      , 14.51428571, 14.7       , 15.0625    , 15.66666667,
       15.7425    , 15.075     , 13.76125   , 14.07777778, 12.76666667,
       14.02222222, 15.63375   , 13.125     , 12.45      , 13.38125   ,
       11.34      , 13.3425    , 13.03125   , 13.35714286, 12.84615385,
       13.05375   , 16.5       , 15.57      , 15.91111111, 13.07571429,
       13.51285714, 12.288     , 13.54444444, 13.72727273, 11.1       ,
       14.86444444, 12.16      , 13.4275    , 12.36111111, 12.68888889,
       13.55714286, 14.63636364, 11.725     , 12.18333333, 13.435     ,
       12.17647059, 13.11666667, 15.6625    , 12.94428571, 14.26666667,
       12.48375   , 15.3125    , 13.45      , 12.9375    , 13.21875   ,
       13.3675    , 12.82571429, 13.8875    , 13.68333333, 14.9625    ,
       14.035     , 12.33      , 12.46      , 14.80571429, 13.7125    ,
       13.46153846, 13.24444444, 12.62142857, 14.14125   , 14.6625    ,
       12.66875   , 11.38461538, 14.22222222, 12.9125    , 12.96666667,
       14.36875   , 12.84285714, 11.225     , 15.125     , 13.06666667,
       12.63636364, 13.3875    , 11.77777778, 14.3775    , 13.04285714,
       14.15      , 12.47142857, 14.0475    , 12.63333333, 14.23333333,
       15.7       , 13.78125   , 14.28625   , 16.8       , 12.82875   ,
       12.75833333, 14.4375    , 12.72857143, 13.12555556, 15.092     ,
       14.56571429, 14.96285714, 17.16666667, 14.77272727, 13.06363636,
       13.40375   , 14.125     , 12.74285714, 13.12857143, 14.93571429,
       13.90625   , 12.41666667, 12.4875    , 14.08571429, 11.50625   ,
       15.28571429, 14.3       , 11.90909091, 11.44444444, 11.7125    ,
       15.88571429, 11.58      , 11.35714286, 12.08333333, 17.69230769,
       15.3       , 11.34714286, 12.18181818, 10.42857143, 13.375     ,
       11.64285714, 13.07142857, 13.58571429, 13.61538462, 12.42      ,
       13.0625    , 12.21428571, 13.08571429, 13.65625   , 13.2325    ,
       13.07375   , 14.78888889, 14.4025    , 16.3875    , 14.98333333,
       13.98333333, 11.61538462, 11.675     , 13.75555556, 14.38888889,
       12.55375   , 12.66571429, 12.11764706, 12.002     , 13.86714286,
       12.675     , 11.575     , 11.63571429, 11.55555556, 13.15      ,
       12.52608696, 16.66666667, 13.20714286, 14.11571429, 13.11111111,
       12.415     , 14.31285714, 14.01428571, 15.925     , 11.80833333,
       11.88888889, 13.30625   , 13.11      , 14.41428571, 13.045     ,
       12.858     , 14.2525    , 11.24285714, 15.07571429, 13.12222222,
       12.6875    , 13.07285714, 12.11666667, 12.56      , 12.77142857,
       13.18181818, 10.72727273, 12.2375    , 12.10526316, 16.6       ,
       15.23076923, 14.575     , 12.41428571, 11.4375    , 14.06666667,
       13.27625   , 12.32142857, 12.75714286, 13.67      , 11.97142857,
       14.13714286, 14.1875    , 14.35      , 11.82      , 14.9       ,
       12.18888889, 14.95555556, 14.4625    , 14.62777778, 14.53333333,
       14.71875   , 15.9       , 12.20555556, 12.62857143, 14.23285714,
       12.22222222, 12.575     , 15.94285714, 10.71428571, 13.32625   ,
       12.32      , 14.75625   , 15.36666667, 11.55      , 14.86363636,
       12.07142857, 12.78571429, 13.8375    , 15.11428571, 11.77142857,
       11.78333333, 14.32857143, 16.33333333, 10.868     , 12.15714286,
       14.53571429, 12.84142857, 13.81375   , 13.04444444, 14.98571429,
       13.661     , 14.2725    , 13.9375    , 14.11      , 14.31666667,
       10.16666667, 13.68142857, 12.61666667, 11.56666667, 14.3625    ,
       13.31375   , 13.41625   , 14.61666667, 14.06      , 12.19230769,
       13.9       , 12.06666667, 12.88625   , 13.88888889, 14.50125   ,
       14.02625   , 14.15375   , 12.45428571, 12.94375   , 14.775     ,
       13.2575    , 11.9625    , 12.81428571, 13.0375    , 14.58888889,
       12.125     , 12.65714286, 13.126     , 11.375     , 13.79857143,
       14.53846154, 12.93875   , 12.88      , 11.8125    , 12.80555556,
       13.475     , 13.26666667, 13.48333333, 17.71428571, 13.65714286,
       13.15428571, 16.09375   , 14.93333333, 13.91      , 12.32857143,
       12.72727273, 14.47142857, 12.67142857, 12.49166667, 11.63636364,
               nan, 11.85625   , 14.46153846, 13.93714286, 14.85      ,
       15.62222222, 13.5425    , 11.92857143, 12.38571429, 13.472     ,
       16.90909091, 12.82      , 12.92307692, 12.36571429, 14.54      ,
       12.73333333, 15.67571429, 13.82      , 13.18333333, 12.65125   ,
       13.95714286, 12.91      , 12.93625   , 14.34125   , 15.12777778,
       15.0125    , 14.21428571, 15.02352941, 13.38333333, 13.09090909,
       13.01125   , 13.65      , 11.736     , 14.51111111, 12.6125    ,
       15.25      , 12.09090909, 14.2125    , 13.51666667, 15.52222222,
       13.9475    , 13.74625   , 13.81714286, 15.55555556, 11.95625   ,
       13.97142857, 13.29      , 15.43333333, 13.78      , 15.11      ,
       15.79857143, 15.6       , 12.48571429, 16.28571429, 14.71666667,
       14.44875   , 12.08428571, 12.15      , 11.8375    , 12.5625    ,
       13.4173913 , 13.24285714, 12.05      , 14.51125   , 13.51428571,
       12.74428571, 13.53333333, 14.75555556, 15.6375    , 13.92727273,
       14.7375    , 14.99285714, 13.01666667, 13.32714286, 10.375     ,
       11.832     , 12.41285714, 12.54571429, 12.51428571, 12.21052632,
       13.29166667, 14.24      , 13.6625    , 11.96666667, 13.3475    ,
       14.925     , 12.11875   , 11.325     , 12.06375   , 14.88875   ,
       11.2625    , 11.08333333])

# Dropping missing values

In [33]:
df = df.dropna()

In [36]:
df.shape

(4405, 37)

In [37]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nationality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17.0,5.0,171.0,1,1,122.0,1,19,12.0,...,0,0.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15.0,1.0,9254.0,1,1,160.0,1,1,3.0,...,0,6.0,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1.0,5.0,9070.0,1,1,122.0,1,37,37.0,...,0,6.0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17.0,2.0,9773.0,1,1,122.0,1,38,37.0,...,0,6.0,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39.0,1.0,8014.0,0,1,100.0,1,37,38.0,...,0,6.0,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

# Converting categorical columns from string to numeric

In [38]:
cols_to_numeric = [
    "Marital status",
    "Nationality",
    "Father's occupation",
    "Displaced",
    "Tuition fees up to date",
    "Age at enrollment",
    "Curricular units 1st sem (credited)"
]

In [39]:
for col in cols_to_numeric:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 4405 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4404 non-null   float64
 1   Application mode                                4405 non-null   float64
 2   Application order                               4405 non-null   float64
 3   Course                                          4405 non-null   float64
 4   Daytime/evening attendance                      4405 non-null   int64
 5   Previous qualification                          4405 non-null   int64
 6   Previous qualification (grade)                  4405 non-null   float64
 7   Nationality                                     4404 non-null   float64
 8   Mother's qualification                          4405 non-null   int64
 9   Father's qualification                          4405 non-null   float64
 10  Mother's occupation                             4405 non-null   float64
 11  Father's occupation                             4404 non-null   float64
 12  Admission grade                                 4405 non-null   float64
 13  Displaced                                       4405 non-null   int64
 14  Educational special needs                       4405 non-null   int64
 15  Debtor                                          4405 non-null   float64
 16  Tuition fees up to date                         4404 non-null   float64
 17  Gender                                          4405 non-null   int64
 18  Scholarship holder                              4405 non-null   int64
 19  Age at enrollment                               4404 non-null   float64
 20  International                                   4405 non-null   float64
 21  Curricular units 1st sem (credited)             4404 non-null   float64
 22  Curricular units 1st sem (enrolled)             4405 non-null   int64
 23  Curricular units 1st sem (evaluations)          4405 non-null   int64
 24  Curricular units 1st sem (approved)             4405 non-null   int64
 25  Curricular units 1st sem (grade)                4405 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4405 non-null   int64
 27  Curricular units 2nd sem (credited)             4405 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4405 non-null   float64
 29  Curricular units 2nd sem (evaluations)          4405 non-null   int64
 30  Curricular units 2nd sem (approved)             4405 non-null   int64
 31  Curricular units 2nd sem (grade)                4405 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4405 non-null   int64
 33  Unemployment rate                               4405 non-null   float64
 34  Inflation rate                                  4405 non-null   float64
 35  GDP                                             4405 non-null   float64
 36  Target                                          4405 non-null   str
dtypes: float64(21), int64(15), str(1)
memory usage: 1.3 MB